export const OrderActionType= {
    SET_CURRENT_PRIORITY_ORDER_LIST: 'SET_CURRENT_PRIORITY_ORDER_LIST',
    ORDER_LIST_ERROR: 'ORDER_LIST_ERROR',
    IS_LOADING: 'IS_LOADING',
    IS_AUTHENTICATE: 'IS_AUTHENTICATE',
  }